drop external  table ext_inttra.wrt_ext_udl_address;
drop external  table ext_inttra.wrt_ext_udl_se_shipment_prod_event_link;
drop external  table ext_inttra.wrt_ext_udl_se_shipment_product_link;
drop external  table ext_inttra.wrt_ext_udl_bk_container_communication;
drop external  table ext_inttra.wrt_ext_udl_bk_container_contact;
drop external  table ext_inttra.wrt_ext_udl_bk_container_line_item;
drop external  table ext_inttra.wrt_ext_udl_bk_location;
drop external  table ext_inttra.wrt_ext_udl_bk_party_communication;
drop external  table ext_inttra.wrt_ext_udl_bl;
drop external  table ext_inttra.wrt_ext_udl_bl_clause;
drop external  table ext_inttra.wrt_ext_udl_bl_container;
drop external  table ext_inttra.wrt_ext_udl_bl_container_line_item;
drop external  table ext_inttra.wrt_ext_udl_bl_current;
drop external  table ext_inttra.wrt_ext_udl_bl_hazmat;
drop external  table ext_inttra.wrt_ext_udl_bl_hazmat_communication;
drop external  table ext_inttra.wrt_ext_udl_bl_hazmat_contact;
drop external  table ext_inttra.wrt_ext_udl_bl_line_item;
drop external  table ext_inttra.wrt_ext_udl_bl_location;
drop external  table ext_inttra.wrt_ext_udl_bl_party;
drop external  table ext_inttra.wrt_ext_udl_bl_party_charge;
drop external  table ext_inttra.wrt_ext_udl_bl_party_charge_reference;
drop external  table ext_inttra.wrt_ext_udl_bl_party_communication;
drop external  table ext_inttra.wrt_ext_udl_bl_party_contact;
drop external  table ext_inttra.wrt_ext_udl_bl_reference;
drop external  table ext_inttra.wrt_ext_udl_bl_si_link;
drop external  table ext_inttra.wrt_ext_udl_bl_transportation;
drop external  table ext_inttra.wrt_ext_udl_booking_comment;
drop external  table ext_inttra.wrt_ext_udl_booking_container_group;
drop external  table ext_inttra.wrt_ext_udl_booking_container_haulage;
drop external  table ext_inttra.wrt_ext_udl_booking_container_reference;
drop external  table ext_inttra.wrt_ext_udl_booking_current;
drop external  table ext_inttra.wrt_ext_udl_booking_hazmat;
drop external  table ext_inttra.wrt_ext_udl_booking_line_item;
drop external  table ext_inttra.wrt_ext_udl_booking_party;
drop external  table ext_inttra.wrt_ext_udl_booking_party_charge;
drop external  table ext_inttra.wrt_ext_udl_booking_party_contact;
drop external  table ext_inttra.wrt_ext_udl_booking_party_document;
drop external  table ext_inttra.wrt_ext_udl_booking_reference;
drop external  table ext_inttra.wrt_ext_udl_booking_split_history;
drop external  table ext_inttra.wrt_ext_udl_booking_subscription;
drop external  table ext_inttra.wrt_ext_udl_booking_transportation;
drop external  table ext_inttra.wrt_ext_udl_business_partner;
drop external  table ext_inttra.wrt_ext_udl_business_partner_service_enrollment;
drop external  table ext_inttra.wrt_ext_udl_company_location;
drop external  table ext_inttra.wrt_ext_udl_company_location_channel_enrollment;
drop external  table ext_inttra.wrt_ext_udl_company_location_service_enrollment;
drop external  table ext_inttra.wrt_ext_udl_company_role;
drop external  table ext_inttra.wrt_ext_udl_container;
drop external  table ext_inttra.wrt_ext_udl_container_event;
drop external  table ext_inttra.wrt_ext_udl_container_event_out;
drop external  table ext_inttra.wrt_ext_udl_container_event_out_reference;
drop external  table ext_inttra.wrt_ext_udl_container_event_out_tloc_date;
drop external  table ext_inttra.wrt_ext_udl_container_event_out_transloc;
drop external  table ext_inttra.wrt_ext_udl_container_event_pending;
drop external  table ext_inttra.wrt_ext_udl_container_event_pending_reference;
drop external  table ext_inttra.wrt_ext_udl_container_event_pending_tloc_date;
drop external  table ext_inttra.wrt_ext_udl_container_event_pending_transloc;
drop external  table ext_inttra.wrt_ext_udl_container_event_reference;
drop external  table ext_inttra.wrt_ext_udl_container_event_revision_current;
drop external  table ext_inttra.wrt_ext_udl_container_event_tloc_date;
drop external  table ext_inttra.wrt_ext_udl_container_event_tloc_date_temp;
drop external  table ext_inttra.wrt_ext_udl_container_event_transloc;
drop external  table ext_inttra.wrt_ext_udl_doc;
drop external  table ext_inttra.wrt_ext_udl_doc_case_link;
drop external  table ext_inttra.wrt_ext_udl_doc_ofac_detail;
drop external  table ext_inttra.wrt_ext_udl_doc_revision;
drop external  table ext_inttra.wrt_ext_udl_doc_transaction;
drop external  table ext_inttra.wrt_ext_udl_eipp_document_link;
drop external  table ext_inttra.wrt_ext_udl_geography_area;
drop external  table ext_inttra.wrt_ext_udl_inv;
drop external  table ext_inttra.wrt_ext_udl_inv_charge_cont_commodity;
drop external  table ext_inttra.wrt_ext_udl_inv_charge_detail;
drop external  table ext_inttra.wrt_ext_udl_inv_charge_tax_detail;
drop external  table ext_inttra.wrt_ext_udl_inv_commodity;
drop external  table ext_inttra.wrt_ext_udl_inv_communication;
drop external  table ext_inttra.wrt_ext_udl_inv_container;
drop external  table ext_inttra.wrt_ext_udl_inv_exchange_rate;
drop external  table ext_inttra.wrt_ext_udl_inv_ntr;
drop external  table ext_inttra.wrt_ext_udl_inv_party;
drop external  table ext_inttra.wrt_ext_udl_inv_party_contact;
drop external  table ext_inttra.wrt_ext_udl_inv_reference;
drop external  table ext_inttra.wrt_ext_udl_inv_transportation_plan;
drop external  table ext_inttra.wrt_ext_udl_inv_version;
drop external  table ext_inttra.wrt_ext_udl_inv_version_comment;
drop external  table ext_inttra.wrt_ext_udl_notification_detail;
drop external  table ext_inttra.wrt_ext_udl_se_shipment_event;
drop external  table ext_inttra.wrt_ext_udl_se_shipment_party;
drop external  table ext_inttra.wrt_ext_udl_se_shipment_party_link;
drop external  table ext_inttra.wrt_ext_udl_se_shipment_party_link_temp;
drop external  table ext_inttra.wrt_ext_udl_se_shipment_party_tp_link;
drop external  table ext_inttra.wrt_ext_udl_security;
drop external  table ext_inttra.wrt_ext_udl_security_detail;
drop external  table ext_inttra.wrt_ext_udl_si;
drop external  table ext_inttra.wrt_ext_udl_si_booking_link;
drop external  table ext_inttra.wrt_ext_udl_si_clause;
drop external  table ext_inttra.wrt_ext_udl_si_container;
drop external  table ext_inttra.wrt_ext_udl_si_container_line_item;
drop external  table ext_inttra.wrt_ext_udl_si_current;
drop external  table ext_inttra.wrt_ext_udl_si_document;
drop external  table ext_inttra.wrt_ext_udl_si_filing_status;
drop external  table ext_inttra.wrt_ext_udl_si_hazmat;
drop external  table ext_inttra.wrt_ext_udl_si_hazmat_communication;
drop external  table ext_inttra.wrt_ext_udl_si_hazmat_contact;
drop external  table ext_inttra.wrt_ext_udl_si_line_item;
drop external  table ext_inttra.wrt_ext_udl_si_line_item_attribute;
drop external  table ext_inttra.wrt_ext_udl_si_line_item_company;
drop external  table ext_inttra.wrt_ext_udl_si_line_item_filing_status;
drop external  table ext_inttra.wrt_ext_udl_si_line_item_reference;
drop external  table ext_inttra.wrt_ext_udl_si_location;
drop external  table ext_inttra.wrt_ext_udl_si_party;
drop external  table ext_inttra.wrt_ext_udl_si_party_communication;
drop external  table ext_inttra.wrt_ext_udl_si_party_contact;
drop external  table ext_inttra.wrt_ext_udl_si_party_reference;
drop external  table ext_inttra.wrt_ext_udl_si_payment_instruction;
drop external  table ext_inttra.wrt_ext_udl_si_reference;
drop external  table ext_inttra.wrt_ext_udl_si_transportation;
drop external  table ext_inttra.wrt_ext_udl_standalone_booking;
drop external  table ext_inttra.wrt_ext_udl_transaction_history;
drop external  table ext_inttra.wrt_ext_udl_transaction_history_detail;
drop external  table ext_inttra.wrt_ext_udl_transaction_reference_key;
drop external  table ext_inttra.wrt_ext_udl_transaction_reference_link;
create writable external table ext_inttra.wrt_ext_udl_address (like udl.udl_address) location ('gpfdist://etl3:8085/udl_address.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bk_container_communication (like udl.udl_bk_container_communication) location ('gpfdist://etl3:8085/udl_bk_container_communication.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bk_container_contact (like udl.udl_bk_container_contact) location ('gpfdist://etl3:8085/udl_bk_container_contact.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bk_container_line_item (like udl.udl_bk_container_line_item) location ('gpfdist://etl3:8085/udl_bk_container_line_item.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bk_location (like udl.udl_bk_location) location ('gpfdist://etl3:8085/udl_bk_location.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bk_party_communication (like udl.udl_bk_party_communication) location ('gpfdist://etl3:8085/udl_bk_party_communication.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl (like udl.udl_bl) location ('gpfdist://etl3:8085/udl_bl.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_clause (like udl.udl_bl_clause) location ('gpfdist://etl3:8085/udl_bl_clause.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_container (like udl.udl_bl_container) location ('gpfdist://etl3:8085/udl_bl_container.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_container_line_item (like udl.udl_bl_container_line_item) location ('gpfdist://etl3:8085/udl_bl_container_line_item.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_current (like udl.udl_bl_current) location ('gpfdist://etl3:8085/udl_bl_current.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_hazmat (like udl.udl_bl_hazmat) location ('gpfdist://etl3:8085/udl_bl_hazmat.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_hazmat_communication (like udl.udl_bl_hazmat_communication) location ('gpfdist://etl3:8085/udl_bl_hazmat_communication.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_hazmat_contact (like udl.udl_bl_hazmat_contact) location ('gpfdist://etl3:8085/udl_bl_hazmat_contact.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_line_item (like udl.udl_bl_line_item) location ('gpfdist://etl3:8085/udl_bl_line_item.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_location (like udl.udl_bl_location) location ('gpfdist://etl3:8085/udl_bl_location.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_party (like udl.udl_bl_party) location ('gpfdist://etl3:8085/udl_bl_party.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_party_charge (like udl.udl_bl_party_charge) location ('gpfdist://etl3:8085/udl_bl_party_charge.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_party_charge_reference (like udl.udl_bl_party_charge_reference) location ('gpfdist://etl3:8085/udl_bl_party_charge_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_party_communication (like udl.udl_bl_party_communication) location ('gpfdist://etl3:8085/udl_bl_party_communication.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_party_contact (like udl.udl_bl_party_contact) location ('gpfdist://etl3:8085/udl_bl_party_contact.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_reference (like udl.udl_bl_reference) location ('gpfdist://etl3:8085/udl_bl_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_si_link (like udl.udl_bl_si_link) location ('gpfdist://etl3:8085/udl_bl_si_link.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_bl_transportation (like udl.udl_bl_transportation) location ('gpfdist://etl3:8085/udl_bl_transportation.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_comment (like udl.udl_booking_comment) location ('gpfdist://etl3:8085/udl_booking_comment.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_container_group (like udl.udl_booking_container_group) location ('gpfdist://etl3:8085/udl_booking_container_group.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_container_haulage (like udl.udl_booking_container_haulage) location ('gpfdist://etl3:8085/udl_booking_container_haulage.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_container_reference (like udl.udl_booking_container_reference) location ('gpfdist://etl3:8085/udl_booking_container_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_current (like udl.udl_booking_current) location ('gpfdist://etl3:8085/udl_booking_current.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_hazmat (like udl.udl_booking_hazmat) location ('gpfdist://etl3:8085/udl_booking_hazmat.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_line_item (like udl.udl_booking_line_item) location ('gpfdist://etl3:8085/udl_booking_line_item.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_party (like udl.udl_booking_party) location ('gpfdist://etl3:8085/udl_booking_party.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_party_charge (like udl.udl_booking_party_charge) location ('gpfdist://etl3:8085/udl_booking_party_charge.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_party_contact (like udl.udl_booking_party_contact) location ('gpfdist://etl3:8085/udl_booking_party_contact.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_party_document (like udl.udl_booking_party_document) location ('gpfdist://etl3:8085/udl_booking_party_document.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_reference (like udl.udl_booking_reference) location ('gpfdist://etl3:8085/udl_booking_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_split_history (like udl.udl_booking_split_history) location ('gpfdist://etl3:8085/udl_booking_split_history.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_subscription (like udl.udl_booking_subscription) location ('gpfdist://etl3:8085/udl_booking_subscription.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_booking_transportation (like udl.udl_booking_transportation) location ('gpfdist://etl3:8085/udl_booking_transportation.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_business_partner (like udl.udl_business_partner) location ('gpfdist://etl3:8085/udl_business_partner.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_business_partner_service_enrollment (like udl.udl_business_partner_service_enrollment) location ('gpfdist://etl3:8085/udl_business_partner_service_enrollment.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_carrier_cust_dev_chanl (like udl.udl_carrier_cust_dev_chanl) location ('gpfdist://etl3:8085/udl_carrier_cust_dev_chanl.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_company_location (like udl.udl_company_location) location ('gpfdist://etl3:8085/udl_company_location.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_company_location_channel_enrollment (like udl.udl_company_location_channel_enrollment) location ('gpfdist://etl3:8085/udl_company_location_channel_enrollment.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_company_location_service_enrollment (like udl.udl_company_location_service_enrollment) location ('gpfdist://etl3:8085/udl_company_location_service_enrollment.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_company_role (like udl.udl_company_role) location ('gpfdist://etl3:8085/udl_company_role.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container (like udl.udl_container) location ('gpfdist://etl3:8085/udl_container.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event (like udl.udl_container_event) location ('gpfdist://etl3:8085/udl_container_event.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_out (like udl.udl_container_event_out) location ('gpfdist://etl3:8085/udl_container_event_out.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_out_reference (like udl.udl_container_event_out_reference) location ('gpfdist://etl3:8085/udl_container_event_out_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_out_tloc_date (like udl.udl_container_event_out_tloc_date) location ('gpfdist://etl3:8085/udl_container_event_out_tloc_date.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_out_transloc (like udl.udl_container_event_out_transloc) location ('gpfdist://etl3:8085/udl_container_event_out_transloc.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_pending (like udl.udl_container_event_pending) location ('gpfdist://etl3:8085/udl_container_event_pending.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_pending_reference (like udl.udl_container_event_pending_reference) location ('gpfdist://etl3:8085/udl_container_event_pending_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_pending_tloc_date (like udl.udl_container_event_pending_tloc_date) location ('gpfdist://etl3:8085/udl_container_event_pending_tloc_date.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_pending_transloc (like udl.udl_container_event_pending_transloc) location ('gpfdist://etl3:8085/udl_container_event_pending_transloc.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_reference (like udl.udl_container_event_reference) location ('gpfdist://etl3:8085/udl_container_event_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_revision_current (like udl.udl_container_event_revision_current) location ('gpfdist://etl3:8085/udl_container_event_revision_current.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_tloc_date (like udl.udl_container_event_tloc_date) location ('gpfdist://etl3:8085/udl_container_event_tloc_date.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_tloc_date_temp (like udl.udl_container_event_tloc_date_temp) location ('gpfdist://etl3:8085/udl_container_event_tloc_date_temp.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_container_event_transloc (like udl.udl_container_event_transloc) location ('gpfdist://etl3:8085/udl_container_event_transloc.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_doc (like udl.udl_doc) location ('gpfdist://etl3:8085/udl_doc.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_doc_case_link (like udl.udl_doc_case_link) location ('gpfdist://etl3:8085/udl_doc_case_link.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_doc_ofac_detail (like udl.udl_doc_ofac_detail) location ('gpfdist://etl3:8085/udl_doc_ofac_detail.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_doc_revision (like udl.udl_doc_revision) location ('gpfdist://etl3:8085/udl_doc_revision.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_doc_transaction (like udl.udl_doc_transaction) location ('gpfdist://etl3:8085/udl_doc_transaction.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_eipp_document_link (like udl.udl_eipp_document_link) location ('gpfdist://etl3:8085/udl_eipp_document_link.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_geography_area (like udl.udl_geography_area) location ('gpfdist://etl3:8085/udl_geography_area.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv (like udl.udl_inv) location ('gpfdist://etl3:8085/udl_inv.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_charge_cont_commodity (like udl.udl_inv_charge_cont_commodity) location ('gpfdist://etl3:8085/udl_inv_charge_cont_commodity.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_charge_detail (like udl.udl_inv_charge_detail) location ('gpfdist://etl3:8085/udl_inv_charge_detail.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_charge_tax_detail (like udl.udl_inv_charge_tax_detail) location ('gpfdist://etl3:8085/udl_inv_charge_tax_detail.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_commodity (like udl.udl_inv_commodity) location ('gpfdist://etl3:8085/udl_inv_commodity.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_communication (like udl.udl_inv_communication) location ('gpfdist://etl3:8085/udl_inv_communication.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_container (like udl.udl_inv_container) location ('gpfdist://etl3:8085/udl_inv_container.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_exchange_rate (like udl.udl_inv_exchange_rate) location ('gpfdist://etl3:8085/udl_inv_exchange_rate.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_ntr (like udl.udl_inv_ntr) location ('gpfdist://etl3:8085/udl_inv_ntr.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_party (like udl.udl_inv_party) location ('gpfdist://etl3:8085/udl_inv_party.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_party_contact (like udl.udl_inv_party_contact) location ('gpfdist://etl3:8085/udl_inv_party_contact.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_reference (like udl.udl_inv_reference) location ('gpfdist://etl3:8085/udl_inv_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_transportation_plan (like udl.udl_inv_transportation_plan) location ('gpfdist://etl3:8085/udl_inv_transportation_plan.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_version (like udl.udl_inv_version) location ('gpfdist://etl3:8085/udl_inv_version.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_inv_version_comment (like udl.udl_inv_version_comment) location ('gpfdist://etl3:8085/udl_inv_version_comment.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_notification_detail (like udl.udl_notification_detail) location ('gpfdist://etl3:8085/udl_notification_detail.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_se_shipment_event (like udl.udl_se_shipment_event) location ('gpfdist://etl3:8085/udl_se_shipment_event.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_se_shipment_party (like udl.udl_se_shipment_party) location ('gpfdist://etl3:8085/udl_se_shipment_party.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_se_shipment_party_link (like udl.udl_se_shipment_party_link) location ('gpfdist://etl3:8085/udl_se_shipment_party_link.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_se_shipment_party_link_temp (like udl.udl_se_shipment_party_link_temp) location ('gpfdist://etl3:8085/udl_se_shipment_party_link_temp.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_se_shipment_party_tp_link (like udl.udl_se_shipment_party_tp_link) location ('gpfdist://etl3:8085/udl_se_shipment_party_tp_link.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_se_shipment_dev_event_link (like udl.udl_se_shipment_dev_event_link) location ('gpfdist://etl3:8085/udl_se_shipment_dev_event_link.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_se_shipment_devuct_link (like udl.udl_se_shipment_devuct_link) location ('gpfdist://etl3:8085/udl_se_shipment_devuct_link.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_security (like udl.udl_security) location ('gpfdist://etl3:8085/udl_security.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_security_detail (like udl.udl_security_detail) location ('gpfdist://etl3:8085/udl_security_detail.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si (like udl.udl_si) location ('gpfdist://etl3:8085/udl_si.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_booking_link (like udl.udl_si_booking_link) location ('gpfdist://etl3:8085/udl_si_booking_link.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_clause (like udl.udl_si_clause) location ('gpfdist://etl3:8085/udl_si_clause.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_container (like udl.udl_si_container) location ('gpfdist://etl3:8085/udl_si_container.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_container_line_item (like udl.udl_si_container_line_item) location ('gpfdist://etl3:8085/udl_si_container_line_item.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_current (like udl.udl_si_current) location ('gpfdist://etl3:8085/udl_si_current.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_document (like udl.udl_si_document) location ('gpfdist://etl3:8085/udl_si_document.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_filing_status (like udl.udl_si_filing_status) location ('gpfdist://etl3:8085/udl_si_filing_status.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_hazmat (like udl.udl_si_hazmat) location ('gpfdist://etl3:8085/udl_si_hazmat.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_hazmat_communication (like udl.udl_si_hazmat_communication) location ('gpfdist://etl3:8085/udl_si_hazmat_communication.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_hazmat_contact (like udl.udl_si_hazmat_contact) location ('gpfdist://etl3:8085/udl_si_hazmat_contact.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_line_item (like udl.udl_si_line_item) location ('gpfdist://etl3:8085/udl_si_line_item.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_line_item_attribute (like udl.udl_si_line_item_attribute) location ('gpfdist://etl3:8085/udl_si_line_item_attribute.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_line_item_company (like udl.udl_si_line_item_company) location ('gpfdist://etl3:8085/udl_si_line_item_company.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_line_item_filing_status (like udl.udl_si_line_item_filing_status) location ('gpfdist://etl3:8085/udl_si_line_item_filing_status.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_line_item_reference (like udl.udl_si_line_item_reference) location ('gpfdist://etl3:8085/udl_si_line_item_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_location (like udl.udl_si_location) location ('gpfdist://etl3:8085/udl_si_location.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_party (like udl.udl_si_party) location ('gpfdist://etl3:8085/udl_si_party.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_party_communication (like udl.udl_si_party_communication) location ('gpfdist://etl3:8085/udl_si_party_communication.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_party_contact (like udl.udl_si_party_contact) location ('gpfdist://etl3:8085/udl_si_party_contact.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_party_reference (like udl.udl_si_party_reference) location ('gpfdist://etl3:8085/udl_si_party_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_payment_instruction (like udl.udl_si_payment_instruction) location ('gpfdist://etl3:8085/udl_si_payment_instruction.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_reference (like udl.udl_si_reference) location ('gpfdist://etl3:8085/udl_si_reference.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_si_transportation (like udl.udl_si_transportation) location ('gpfdist://etl3:8085/udl_si_transportation.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_standalone_booking (like udl.udl_standalone_booking) location ('gpfdist://etl3:8085/udl_standalone_booking.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_transaction_history (like udl.udl_transaction_history) location ('gpfdist://etl3:8085/udl_transaction_history.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_transaction_history_detail (like udl.udl_transaction_history_detail) location ('gpfdist://etl3:8085/udl_transaction_history_detail.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_transaction_reference_key (like udl.udl_transaction_reference_key) location ('gpfdist://etl3:8085/udl_transaction_reference_key.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
create writable external table ext_inttra.wrt_ext_udl_transaction_reference_link (like udl.udl_transaction_reference_link) location ('gpfdist://etl3:8085/udl_transaction_reference_link.txt') format 'text' (delimiter '^'  null '' escape 'OFF') ENCODING 'LATIN1';
ALTER TABLE ext_inttra.wrt_ext_udl_address OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bk_container_communication OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bk_container_contact OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bk_container_line_item OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bk_location OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bk_party_communication OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_clause OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_container OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_container_line_item OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_current OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_hazmat OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_hazmat_communication OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_hazmat_contact OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_line_item OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_location OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_party OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_party_charge OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_party_charge_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_party_communication OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_party_contact OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_si_link OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_bl_transportation OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_comment OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_container_group OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_container_haulage OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_container_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_current OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_hazmat OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_line_item OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_party OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_party_charge OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_party_contact OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_party_document OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_split_history OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_subscription OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_booking_transportation OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_business_partner OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_business_partner_service_enrollment OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_carrier_cust_dev_chanl OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_company_location OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_company_location_channel_enrollment OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_company_location_service_enrollment OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_company_role OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_out OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_out_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_out_tloc_date OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_out_transloc OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_pending OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_pending_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_pending_tloc_date OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_pending_transloc OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_revision_current OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_tloc_date OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_tloc_date_temp OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_container_event_transloc OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_doc OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_doc_case_link OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_doc_ofac_detail OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_doc_revision OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_doc_transaction OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_eipp_document_link OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_geography_area OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_charge_cont_commodity OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_charge_detail OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_charge_tax_detail OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_commodity OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_communication OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_container OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_exchange_rate OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_ntr OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_party OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_party_contact OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_transportation_plan OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_version OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_inv_version_comment OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_notification_detail OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_se_shipment_event OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_se_shipment_party OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_se_shipment_party_link OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_se_shipment_party_link_temp OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_se_shipment_party_tp_link OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_se_shipment_dev_event_link OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_se_shipment_devuct_link OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_security OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_security_detail OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_booking_link OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_clause OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_container OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_container_line_item OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_current OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_document OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_filing_status OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_hazmat OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_hazmat_communication OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_hazmat_contact OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_line_item OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_line_item_attribute OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_line_item_company OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_line_item_filing_status OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_line_item_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_location OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_party OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_party_communication OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_party_contact OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_party_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_payment_instruction OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_reference OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_si_transportation OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_standalone_booking OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_transaction_history OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_transaction_history_detail OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_transaction_reference_key OWNER TO edwstg_prod;
ALTER TABLE ext_inttra.wrt_ext_udl_transaction_reference_link OWNER TO edwstg_prod;
